version: "3.7"
name: s3-liferay-oauth-client-extension
services:
  s3-liferay:
    image: liferay/dxp:2023.q4.6
    container_name: s3-liferay-2023Q46
    depends_on:
       - s3-apim
    environment:
      LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_DELAY: 10
      LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_MAX_PERIOD_RETRIES: 10
      LIFERAY_JVM_OPTS: "-Xms2560m -Xmx4096m"
      # Used by .config files to create client extensions as remote apps in Liferay Control Panel
      APP1_REMOTE_DOMAIN: "http://app1.dev.local:3000"
    networks: 
      - s3-network
    ports: 
      - 8080:8080
      - 127.0.0.1:11311:11311
    volumes:
      - ./liferay-74/mount:/mnt/liferay
      - s3-liferay-tools:/opt/liferay/tools
      - s3-liferay-data:/opt/liferay/data
      - s3-liferay-osgi-configs:/opt/liferay/osgi/configs
      - s3-liferay-osgi-marketplace:/opt/liferay/osgi/marketplace
      - s3-liferay-osgi-modules:/opt/liferay/osgi/modules
      - s3-liferay-osgi-war:/opt/liferay/osgi/war
  s3-apim:
    image: kong/kong-gateway:3.6.0.0
    container_name: s3-apim
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
    networks: 
      - s3-network
    ports: 
      - 8800:8000
      - 8443:8443
      - 8001:8001  
      - 8444:8444
      - 8002:8002  
      - 8445:8445  
      - 8003:8003  
      - 8004:8004
    volumes:
      - ./kong/declarative:/kong/declarative/
  s3-app1:
    container_name: s3-app1-react-docker
    build:
      context: ../front-end/app1-docker-example
    networks:
      - s3-network
    ports:
      - 3000:3000
    volumes:
      - ../front-end/app1-docker-example:/app/app1-docker-example
      - /app/app1-docker-example/node_modules
networks:
  s3-network:
    name: s3-network
volumes:
  s3-liferay-data:
  s3-liferay-tools:
  s3-liferay-osgi-configs:
  s3-liferay-osgi-marketplace:
  s3-liferay-osgi-modules:
  s3-liferay-osgi-war: