########################################## Get tokens : Authorization Code  ##########################################
GET http://portal.dev.local:8080/o/oauth2/authorize
 
Content-Type: application/x-www-form-urlencoded
client_id=id-6fb14480-a7c3-3d16-f828-a93d7bfadd2
&response_type=code